
tcp_port_range_scanner:
  enable: False
  hosts:
    - 192.168.1.18
  port_range: [22, 23, 80, 443, 3389]

ack_scanner:
  enable: False
  hosts:
    - 192.168.1.1
    - 192.168.1.10
    - 192.168.1.11
    - 192.168.1.12
    - 192.168.1.17
    - 192.168.1.18
    - 192.168.1.22
  dports: [80, 255]

xmas_scanner:
  enable: False
  hosts:
    - 192.168.1.1
    - 192.168.1.10
    - 192.168.1.11
    - 192.168.1.12
    - 192.168.1.17
    - 192.168.1.18
    - 192.168.1.22
  dports: [255]

ip_scanner:
  enable: False
  hosts:
    - 192.168.1.1
    - 192.168.1.10
    - 192.168.1.11
    - 192.168.1.12
    - 192.168.1.17
    - 192.168.1.18
    - 192.168.1.22
  message: "SCAPY"

arp_scanner:
  enable: False
  network: '192.168.1.0/24'

icmp_ping_scanner:
  enable: False
  enable: True
  network: '192.168.1.0/24'
  nb_host_to_test: 10

udp_ping:
  enable: False
  hosts:
    - 192.168.*.1
    - 192.168.1.10-13

dns_request:
  enable: False
  dns_server: '8.8.8.8'
  dport: 53
  hosts:
    - www.google.fr
    - www.thepacketgeek.com
    - www.ovh.fr

http_request:
  enable: False
  dport: 80
  hosts:
    - www.google.fr
    - www.thepacketgeek.com
    - www.ovh.fr

ping_of_the_death:
  enable: False
  hosts:
    - 192.168.1.10
    - 192.168.1.11